definitions:
  services:
    docker: # default docker service
      type: docker 
      # memory: 512
pipelines:
  custom:
    customPipelineWithRunnerStep:
      - step:
          name: Step 1
          services:
            - "docker"
          runs-on: 
            - 'self.hosted'
            - 'linux'
          script:
          - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
          - docker build -t josegrelnx/python-calc:latest .
          - docker push josegrelnx/python-calc:latest